services:
  api:
    image: visualdynamics/api:dev
    build:
      context: .
      dockerfile: apps/api/dev.Dockerfile
    restart: always
    command: ["pnpm", "--filter", "api", "start:dev"]
    env_file: .env
    depends_on:
      - redis
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
      - files:/files
      - /usr/local/gromacs:/gromacs
      - /app/node_modules
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # or all
              capabilities: [gpu]

  web:
    build:
      context: .
      dockerfile: apps/web/dev.Dockerfile
    restart: always
    image: visualdynamics/web:dev
    command: ["pnpm", "--filter", "web", "dev", "--", "--host"]
    ports:
      - "3000:5173"
    volumes:
      - ./:/app
      - /app/node_modules

  redis:
    image: redis:alpine
    command: redis-server --maxmemory-policy noeviction
    restart: always
    volumes:
      - redis:/data

volumes:
  redis:
    driver: nfsvol
  files:
    driver: nfsvol
