services:
  redis:
    image: redis:alpine
    command: redis-server --maxmemory-policy noeviction
    restart: always
    networks:
      - traefik
    volumes:
      - redis:/data

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:5173"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`visualdynamics.fiocruz.br`)"
      - "traefik.http.routers.web.service=web"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
      - "traefik.http.routers.web.tls.domains[0].main=visualdynamics.fiocruz.br"
      - "traefik.http.routers.web.entryPoints=websecure"
    env_file: .env
    restart: always
    networks:
      - traefik
    image: visualdynamics/web:latest

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file: .env
    ports:
      - "3001:3000"
    restart: always
    networks:
      - traefik
    image: visualdynamics/api:latest
    volumes:
      - data:/files
      - /usr/local/gromacs:/gromacs
    depends_on:
      - redis

  traefik:
    restart: always
    image: traefik
    command:
      # - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.watch"
      - "--providers.docker.network=traefik"
      - "--providers.docker.exposedByDefault=false"

      - "--certificatesresolvers.letsencrypt.acme.email=labioquim@fiocruz.br" # replace with your email
      - "--certificatesresolvers.letsencrypt.acme.storage=acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0"

      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.web.http.redirections.entrypoint.permanent=true"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_acme:/acme
      - traefik_logs:/logs
    ports:
      - "80:80"
      - "443:443"

volumes:
  data:
    driver: nfsvol
  redis:
    driver: nfsvol
  traefik_acme:
    driver: nfsvol
  traefik_logs:
    driver: nfsvol

networks:
  traefik:
    external: true
  default:
