name: visualdynamics
channels:
  - conda-forge
  - defaults
dependencies:
  - celery=5.3.1
  - flask=2.3.2
  - flask-cors=3.0.10
  - flask-restful=0.3.9
  - flower=1.2.0
  - pip=23.1.2
  - pyopenssl=23.2.0
  - python=3.11.3
  - requests=2.29.0
  - pip:
      - redis==4.6.0
