packages:
  - "apps/*"

onlyBuild:
  "@nestjs/core": true
  "@parcel/watcher": true
  "@prisma/engines": true
  "@scarf/scarf": true
  "esbuild": true
  "msgpackr-extract": true
  "prisma": true

shamefullyHoist: true
nodeLinker: hoisted