packages:
  - "apps/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
nodeLinker: hoisted

onlyBuild:
  "@nestjs/core": true
  "@parcel/watcher": true
  "@prisma/engines": true
  "@scarf/scarf": true
  "esbuild": true
  "msgpackr-extract": true
  "prisma": true

shamefullyHoist: true
