#!/bin/bash
SHELL_NAME="${SHELL##*/}"

############################################################
# Help                                                     #
############################################################
Help() {
  # Display Help
  echo "How to run VisualDynamics?"
  echo
  echo "Syntax: ./run -{option}"
  echo "options:"
  echo "h     Print this Help."
  echo "i     Installs (or reinstalls) VisualDynamics."
  echo "m     Specify the execution mode (dev|prod|server)."
  echo
}

############################################################
# StartService                                             #
############################################################
StartService() {  
  if [ $1 == 'dev' ] || [ $1 == 'prod' ] || [ $1 == 'server' ]; then
    echo ">> Starting VisualDynamics in $1 mode"
    echo ">> To end the server press Ctrl + C"
  fi

  eval "$(/home/$USER/.conda/bin/conda shell.$SHELL_NAME hook)"
  conda activate visualdynamics
  source config

  if [ $1 == 'dev' ]; then
    export FLASK_ENV=development
    flask run --host=0.0.0.0
  elif [ $1 == 'prod' ]; then
    echo ">> Staring server on http://0.0.0.0:8080"
    python3 visualdynamics.py
  elif [ $1 == 'server' ]; then
    export FLASK_ENV=production
    flask run --host=0.0.0.0 --port=8080
  else
    echo "Invalid Start Mode: $1"
  fi
}

############################################################
# InstallService                                           #
############################################################
InstallService() {
  export PIP_IGNORE_INSTALLED=0

  echo "=> BEWARE. All data stored in the app/app.db will be lost."
  echo "=> This is a automated process mainly, you might need to enter your password by continuing"
  read -sn1 -p "==> Do you wish to continue? (Y/n) " resp
  resp=${resp:-Y}

  if [ $resp = 'Y' ] || [ $resp = 'y' ]; then
    echo
    chmod +x ./scripts/config.sh
    source ./scripts/config.sh
    source config
    echo
    if type "conda" &> /dev/null
    then
      echo "=> Miniconda found, skipping..."
    else
      echo "=> Installing Miniconda"
      echo "==> Miniconda will be installed on $HOME/.conda/"
      echo "==> It is highly recommended that you accept to run 'conda init'"
      echo "==> at the end of the miniconda install. If you forgot, you can"
      echo "==> run 'source ~/.conda/bin/activate' and then run 'conda init'"
      curl --progress-bar https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh > miniconda.sh
      chmod +x miniconda.sh
      bash miniconda.sh -b -p $HOME/.conda
      eval "$(/home/$USER/.conda/bin/conda shell.$SHELL_NAME hook)"
      conda init $SHELL_NAME
      echo "==> Miniconda installed to $HOME/.conda/"
    fi

    echo "=> Verifying and Installing Dependencies"
    if [ -f "/etc/arch-release" ]; then
      chmod +x ./scripts/arch-steps.sh
      source ./scripts/arch-steps.sh
    else
      chmod +x ./scripts/debian-steps.sh
      source ./scripts/debian-steps.sh
    fi

    chmod +x ./scripts/gromacs.sh
    source ./scripts/gromacs.sh

    echo "=> Dependencies OK!"

    echo "=> Initializing Environment and Dependencies"
    eval "$(/home/$USER/.conda/bin/conda shell.$SHELL_NAME hook)"
    # Init and install Conda and Project Dependencies
    if ! { conda env list | grep 'visualdynamics'; } >/dev/null 2>&1; then
      conda env create -f ./environment.yml
    fi
    conda activate visualdynamics
    echo "=> Environment and Dependencies Initialized"

    echo "=> Resetting database"
    # Clear our SQLite DB
    python3 clear_database.py
    echo "=> Database resetted"

    # Compile our app translations
    echo "=> Readying translations"
    flask translate compile > /dev/null 2>&1
    echo "=> Translations ready"

    echo "=> Finishing things up..."
    # Make sure our DB and our md_pr file don't go to VCS
    git update-index --assume-unchanged app/app.db mdpfiles/md_pr.mdp

    # Make our app starters executable
    chmod +x run

    echo "> VisualDynamics is now ready. See ./run -h to start the application"  
  elif [ $resp = 'n' ]; then
    echo "Installation Cancelled by User"
  else
    echo "Invalid Option"
  fi
}

############################################################
# Main program                                             #
############################################################
while getopts ":him:" option; do
  case $option in
    h) # display Help
      Help
      exit;;
    i)
      InstallService;;
    m) # start the application in the selected mode
      StartService "$OPTARG";;
    \?) # Invalid option
      echo "Error: Invalid option"
      exit;;
  esac
done

