#!/bin/bash
SHELL_NAME="${SHELL##*/}"

############################################################
# Help                                                     #
############################################################
Help() {
  # Display Help
  echo "How to run VisualDynamics?"
  echo
  echo "Syntax: ./run -{option}"
  echo "options:"
  echo "h     Print this Help."
  echo "i     Installs (or reinstalls) VisualDynamics. (none|gpu)"
  echo "m     Specify the execution mode (dev|prod|server)."
  echo
}

############################################################
# StartService                                             #
############################################################
StartService() {  
  if [ $1 == 'dev' ] || [ $1 == 'prod' ] || [ $1 == 'server' ]; then
    echo ">> Starting VisualDynamics in $1 mode"
    echo ">> To end the server press Ctrl + C"
  fi

	re="base environment : /[a-zA-Z]+/[a-zA-Z]+/[A-Za-z0-9.]+\s \(writable\)"
	CONDA_INFO="$(conda info)"
	if [[ $CONDA_INFO =~ $re ]]; then
		BASE_ENV=${BASH_REMATCH}

		re2="/[a-zA-Z]+/[a-zA-Z]+/[A-Za-z0-9.]+\s"

		if [[ $BASE_ENV =~ $re2 ]]; then
			CONDA_PATH="${BASH_REMATCH}"
		fi
	fi

  eval "$($CONDA_PATH/bin/conda shell.$SHELL_NAME hook)"
  conda activate visualdynamics
  source config

  if [ $1 == 'dev' ]; then
    export FLASK_ENV=development
    flask run --host=0.0.0.0
  elif [ $1 == 'prod' ]; then
    echo ">> Staring server on http://0.0.0.0:8080"
    python3 visualdynamics.py
  elif [ $1 == 'server' ]; then
    export FLASK_ENV=production
    flask run --host=0.0.0.0 --port=8080
  else
    echo "Invalid Start Mode: $1"
  fi
}

############################################################
# InstallService                                           #
############################################################
InstallService() {
  echo "=> BEWARE. All data stored in the app/app.db will be lost."
  echo "=> This is a automated process mainly, you might need to enter your password by continuing"
  read -sn1 -p "==> Do you wish to continue? (Y/n) " resp
  resp=${resp:-Y}
  echo
  if [ $resp = 'Y' ] || [ $resp = 'y' ]; then
    source ./scripts/install.sh
  elif [ $resp = 'n' ]; then
    echo "Installation Cancelled by User"
  else
    echo "Invalid Option"
  fi
}

############################################################
# Main program                                             #
############################################################
while getopts ":him:" option; do
  case $option in
    h) # display Help
      Help
      exit;;
    i) # Install the application
      InstallService;;
    m) # start the application in the selected mode
      StartService "$OPTARG";;
    \?) # Invalid option
      echo "Error: Invalid option"
      exit;;
  esac
done

