/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTermsOfServiceRouteImport } from './routes/_public/terms-of-service'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicGuidesRouteImport } from './routes/_public/guides'
import { Route as PublicAnalyticsRouteImport } from './routes/_public/analytics'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ProtectedSimulationsRouteRouteImport } from './routes/_protected/simulations/route'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedSimulationsIndexRouteImport } from './routes/_protected/simulations/index'
import { Route as ProtectedSimulationsSimulationIdRouteImport } from './routes/_protected/simulations/$simulationId'
import { Route as ProtectedAdminSettingsRouteImport } from './routes/_protected/admin/settings'
import { Route as ProtectedSimulationsSubmitRouteRouteImport } from './routes/_protected/simulations/submit/route'
import { Route as ProtectedAdminUsersRouteRouteImport } from './routes/_protected/admin/users/route'
import { Route as ProtectedAdminToolsRouteRouteImport } from './routes/_protected/admin/tools/route'
import { Route as ProtectedAdminSimulationsRouteRouteImport } from './routes/_protected/admin/simulations/route'
import { Route as ProtectedAdminFlagsRouteRouteImport } from './routes/_protected/admin/flags/route'
import { Route as ProtectedSimulationsSubmitIndexRouteImport } from './routes/_protected/simulations/submit/index'
import { Route as ProtectedAdminUsersIndexRouteImport } from './routes/_protected/admin/users/index'
import { Route as ProtectedAdminToolsIndexRouteImport } from './routes/_protected/admin/tools/index'
import { Route as ProtectedAdminSimulationsIndexRouteImport } from './routes/_protected/admin/simulations/index'
import { Route as ProtectedAdminServerIndexRouteImport } from './routes/_protected/admin/server/index'
import { Route as ProtectedAdminFlagsIndexRouteImport } from './routes/_protected/admin/flags/index'
import { Route as ProtectedAdminSimulationsSimulationIdRouteImport } from './routes/_protected/admin/simulations/$simulationId'
import { Route as ProtectedAdminFlagsNewRouteImport } from './routes/_protected/admin/flags/new'
import { Route as ProtectedAdminFlagsKeyRouteImport } from './routes/_protected/admin/flags/$key'
import { Route as ProtectedAdminUsersUserIdRouteRouteImport } from './routes/_protected/admin/users/$userId/route'
import { Route as ProtectedAdminToolsUserImporterRouteRouteImport } from './routes/_protected/admin/tools/user-importer/route'
import { Route as ProtectedAdminToolsSimulationImporterRouteRouteImport } from './routes/_protected/admin/tools/simulation-importer/route'
import { Route as ProtectedAdminToolsBatchEmailRouteRouteImport } from './routes/_protected/admin/tools/batch-email/route'
import { Route as ProtectedAdminUsersUserIdIndexRouteImport } from './routes/_protected/admin/users/$userId/index'
import { Route as ProtectedAdminToolsUserImporterIndexRouteImport } from './routes/_protected/admin/tools/user-importer/index'
import { Route as ProtectedAdminToolsSimulationImporterIndexRouteImport } from './routes/_protected/admin/tools/simulation-importer/index'
import { Route as ProtectedAdminToolsBatchEmailIndexRouteImport } from './routes/_protected/admin/tools/batch-email/index'
import { Route as ProtectedAdminUsersUserIdFolderIndexRouteImport } from './routes/_protected/admin/users/$userId/folder/index'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsOfServiceRoute = PublicTermsOfServiceRouteImport.update({
  id: '/_public/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/_public/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicGuidesRoute = PublicGuidesRouteImport.update({
  id: '/_public/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAnalyticsRoute = PublicAnalyticsRouteImport.update({
  id: '/_public/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/_public/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedSimulationsRouteRoute =
  ProtectedSimulationsRouteRouteImport.update({
    id: '/simulations',
    path: '/simulations',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSimulationsIndexRoute =
  ProtectedSimulationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSimulationsRouteRoute,
  } as any)
const ProtectedSimulationsSimulationIdRoute =
  ProtectedSimulationsSimulationIdRouteImport.update({
    id: '/$simulationId',
    path: '/$simulationId',
    getParentRoute: () => ProtectedSimulationsRouteRoute,
  } as any)
const ProtectedAdminSettingsRoute = ProtectedAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedSimulationsSubmitRouteRoute =
  ProtectedSimulationsSubmitRouteRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => ProtectedSimulationsRouteRoute,
  } as any)
const ProtectedAdminUsersRouteRoute =
  ProtectedAdminUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminToolsRouteRoute =
  ProtectedAdminToolsRouteRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminSimulationsRouteRoute =
  ProtectedAdminSimulationsRouteRouteImport.update({
    id: '/simulations',
    path: '/simulations',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminFlagsRouteRoute =
  ProtectedAdminFlagsRouteRouteImport.update({
    id: '/flags',
    path: '/flags',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedSimulationsSubmitIndexRoute =
  ProtectedSimulationsSubmitIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSimulationsSubmitRouteRoute,
  } as any)
const ProtectedAdminUsersIndexRoute =
  ProtectedAdminUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdminUsersRouteRoute,
  } as any)
const ProtectedAdminToolsIndexRoute =
  ProtectedAdminToolsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdminToolsRouteRoute,
  } as any)
const ProtectedAdminSimulationsIndexRoute =
  ProtectedAdminSimulationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdminSimulationsRouteRoute,
  } as any)
const ProtectedAdminServerIndexRoute =
  ProtectedAdminServerIndexRouteImport.update({
    id: '/server/',
    path: '/server/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminFlagsIndexRoute =
  ProtectedAdminFlagsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdminFlagsRouteRoute,
  } as any)
const ProtectedAdminSimulationsSimulationIdRoute =
  ProtectedAdminSimulationsSimulationIdRouteImport.update({
    id: '/$simulationId',
    path: '/$simulationId',
    getParentRoute: () => ProtectedAdminSimulationsRouteRoute,
  } as any)
const ProtectedAdminFlagsNewRoute = ProtectedAdminFlagsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedAdminFlagsRouteRoute,
} as any)
const ProtectedAdminFlagsKeyRoute = ProtectedAdminFlagsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ProtectedAdminFlagsRouteRoute,
} as any)
const ProtectedAdminUsersUserIdRouteRoute =
  ProtectedAdminUsersUserIdRouteRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ProtectedAdminUsersRouteRoute,
  } as any)
const ProtectedAdminToolsUserImporterRouteRoute =
  ProtectedAdminToolsUserImporterRouteRouteImport.update({
    id: '/user-importer',
    path: '/user-importer',
    getParentRoute: () => ProtectedAdminToolsRouteRoute,
  } as any)
const ProtectedAdminToolsSimulationImporterRouteRoute =
  ProtectedAdminToolsSimulationImporterRouteRouteImport.update({
    id: '/simulation-importer',
    path: '/simulation-importer',
    getParentRoute: () => ProtectedAdminToolsRouteRoute,
  } as any)
const ProtectedAdminToolsBatchEmailRouteRoute =
  ProtectedAdminToolsBatchEmailRouteRouteImport.update({
    id: '/batch-email',
    path: '/batch-email',
    getParentRoute: () => ProtectedAdminToolsRouteRoute,
  } as any)
const ProtectedAdminUsersUserIdIndexRoute =
  ProtectedAdminUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdminUsersUserIdRouteRoute,
  } as any)
const ProtectedAdminToolsUserImporterIndexRoute =
  ProtectedAdminToolsUserImporterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdminToolsUserImporterRouteRoute,
  } as any)
const ProtectedAdminToolsSimulationImporterIndexRoute =
  ProtectedAdminToolsSimulationImporterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdminToolsSimulationImporterRouteRoute,
  } as any)
const ProtectedAdminToolsBatchEmailIndexRoute =
  ProtectedAdminToolsBatchEmailIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdminToolsBatchEmailRouteRoute,
  } as any)
const ProtectedAdminUsersUserIdFolderIndexRoute =
  ProtectedAdminUsersUserIdFolderIndexRouteImport.update({
    id: '/folder/',
    path: '/folder/',
    getParentRoute: () => ProtectedAdminUsersUserIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/simulations': typeof ProtectedSimulationsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/about': typeof PublicAboutRoute
  '/analytics': typeof PublicAnalyticsRoute
  '/guides': typeof PublicGuidesRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms-of-service': typeof PublicTermsOfServiceRoute
  '/admin/flags': typeof ProtectedAdminFlagsRouteRouteWithChildren
  '/admin/simulations': typeof ProtectedAdminSimulationsRouteRouteWithChildren
  '/admin/tools': typeof ProtectedAdminToolsRouteRouteWithChildren
  '/admin/users': typeof ProtectedAdminUsersRouteRouteWithChildren
  '/simulations/submit': typeof ProtectedSimulationsSubmitRouteRouteWithChildren
  '/admin/settings': typeof ProtectedAdminSettingsRoute
  '/simulations/$simulationId': typeof ProtectedSimulationsSimulationIdRoute
  '/simulations/': typeof ProtectedSimulationsIndexRoute
  '/admin/tools/batch-email': typeof ProtectedAdminToolsBatchEmailRouteRouteWithChildren
  '/admin/tools/simulation-importer': typeof ProtectedAdminToolsSimulationImporterRouteRouteWithChildren
  '/admin/tools/user-importer': typeof ProtectedAdminToolsUserImporterRouteRouteWithChildren
  '/admin/users/$userId': typeof ProtectedAdminUsersUserIdRouteRouteWithChildren
  '/admin/flags/$key': typeof ProtectedAdminFlagsKeyRoute
  '/admin/flags/new': typeof ProtectedAdminFlagsNewRoute
  '/admin/simulations/$simulationId': typeof ProtectedAdminSimulationsSimulationIdRoute
  '/admin/flags/': typeof ProtectedAdminFlagsIndexRoute
  '/admin/server/': typeof ProtectedAdminServerIndexRoute
  '/admin/simulations/': typeof ProtectedAdminSimulationsIndexRoute
  '/admin/tools/': typeof ProtectedAdminToolsIndexRoute
  '/admin/users/': typeof ProtectedAdminUsersIndexRoute
  '/simulations/submit/': typeof ProtectedSimulationsSubmitIndexRoute
  '/admin/tools/batch-email/': typeof ProtectedAdminToolsBatchEmailIndexRoute
  '/admin/tools/simulation-importer/': typeof ProtectedAdminToolsSimulationImporterIndexRoute
  '/admin/tools/user-importer/': typeof ProtectedAdminToolsUserImporterIndexRoute
  '/admin/users/$userId/': typeof ProtectedAdminUsersUserIdIndexRoute
  '/admin/users/$userId/folder/': typeof ProtectedAdminUsersUserIdFolderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/about': typeof PublicAboutRoute
  '/analytics': typeof PublicAnalyticsRoute
  '/guides': typeof PublicGuidesRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms-of-service': typeof PublicTermsOfServiceRoute
  '/admin/settings': typeof ProtectedAdminSettingsRoute
  '/simulations/$simulationId': typeof ProtectedSimulationsSimulationIdRoute
  '/simulations': typeof ProtectedSimulationsIndexRoute
  '/admin/flags/$key': typeof ProtectedAdminFlagsKeyRoute
  '/admin/flags/new': typeof ProtectedAdminFlagsNewRoute
  '/admin/simulations/$simulationId': typeof ProtectedAdminSimulationsSimulationIdRoute
  '/admin/flags': typeof ProtectedAdminFlagsIndexRoute
  '/admin/server': typeof ProtectedAdminServerIndexRoute
  '/admin/simulations': typeof ProtectedAdminSimulationsIndexRoute
  '/admin/tools': typeof ProtectedAdminToolsIndexRoute
  '/admin/users': typeof ProtectedAdminUsersIndexRoute
  '/simulations/submit': typeof ProtectedSimulationsSubmitIndexRoute
  '/admin/tools/batch-email': typeof ProtectedAdminToolsBatchEmailIndexRoute
  '/admin/tools/simulation-importer': typeof ProtectedAdminToolsSimulationImporterIndexRoute
  '/admin/tools/user-importer': typeof ProtectedAdminToolsUserImporterIndexRoute
  '/admin/users/$userId': typeof ProtectedAdminUsersUserIdIndexRoute
  '/admin/users/$userId/folder': typeof ProtectedAdminUsersUserIdFolderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_protected/simulations': typeof ProtectedSimulationsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/analytics': typeof PublicAnalyticsRoute
  '/_public/guides': typeof PublicGuidesRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms-of-service': typeof PublicTermsOfServiceRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/admin/flags': typeof ProtectedAdminFlagsRouteRouteWithChildren
  '/_protected/admin/simulations': typeof ProtectedAdminSimulationsRouteRouteWithChildren
  '/_protected/admin/tools': typeof ProtectedAdminToolsRouteRouteWithChildren
  '/_protected/admin/users': typeof ProtectedAdminUsersRouteRouteWithChildren
  '/_protected/simulations/submit': typeof ProtectedSimulationsSubmitRouteRouteWithChildren
  '/_protected/admin/settings': typeof ProtectedAdminSettingsRoute
  '/_protected/simulations/$simulationId': typeof ProtectedSimulationsSimulationIdRoute
  '/_protected/simulations/': typeof ProtectedSimulationsIndexRoute
  '/_protected/admin/tools/batch-email': typeof ProtectedAdminToolsBatchEmailRouteRouteWithChildren
  '/_protected/admin/tools/simulation-importer': typeof ProtectedAdminToolsSimulationImporterRouteRouteWithChildren
  '/_protected/admin/tools/user-importer': typeof ProtectedAdminToolsUserImporterRouteRouteWithChildren
  '/_protected/admin/users/$userId': typeof ProtectedAdminUsersUserIdRouteRouteWithChildren
  '/_protected/admin/flags/$key': typeof ProtectedAdminFlagsKeyRoute
  '/_protected/admin/flags/new': typeof ProtectedAdminFlagsNewRoute
  '/_protected/admin/simulations/$simulationId': typeof ProtectedAdminSimulationsSimulationIdRoute
  '/_protected/admin/flags/': typeof ProtectedAdminFlagsIndexRoute
  '/_protected/admin/server/': typeof ProtectedAdminServerIndexRoute
  '/_protected/admin/simulations/': typeof ProtectedAdminSimulationsIndexRoute
  '/_protected/admin/tools/': typeof ProtectedAdminToolsIndexRoute
  '/_protected/admin/users/': typeof ProtectedAdminUsersIndexRoute
  '/_protected/simulations/submit/': typeof ProtectedSimulationsSubmitIndexRoute
  '/_protected/admin/tools/batch-email/': typeof ProtectedAdminToolsBatchEmailIndexRoute
  '/_protected/admin/tools/simulation-importer/': typeof ProtectedAdminToolsSimulationImporterIndexRoute
  '/_protected/admin/tools/user-importer/': typeof ProtectedAdminToolsUserImporterIndexRoute
  '/_protected/admin/users/$userId/': typeof ProtectedAdminUsersUserIdIndexRoute
  '/_protected/admin/users/$userId/folder/': typeof ProtectedAdminUsersUserIdFolderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/simulations'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/about'
    | '/analytics'
    | '/guides'
    | '/privacy'
    | '/terms-of-service'
    | '/admin/flags'
    | '/admin/simulations'
    | '/admin/tools'
    | '/admin/users'
    | '/simulations/submit'
    | '/admin/settings'
    | '/simulations/$simulationId'
    | '/simulations/'
    | '/admin/tools/batch-email'
    | '/admin/tools/simulation-importer'
    | '/admin/tools/user-importer'
    | '/admin/users/$userId'
    | '/admin/flags/$key'
    | '/admin/flags/new'
    | '/admin/simulations/$simulationId'
    | '/admin/flags/'
    | '/admin/server/'
    | '/admin/simulations/'
    | '/admin/tools/'
    | '/admin/users/'
    | '/simulations/submit/'
    | '/admin/tools/batch-email/'
    | '/admin/tools/simulation-importer/'
    | '/admin/tools/user-importer/'
    | '/admin/users/$userId/'
    | '/admin/users/$userId/folder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/about'
    | '/analytics'
    | '/guides'
    | '/privacy'
    | '/terms-of-service'
    | '/admin/settings'
    | '/simulations/$simulationId'
    | '/simulations'
    | '/admin/flags/$key'
    | '/admin/flags/new'
    | '/admin/simulations/$simulationId'
    | '/admin/flags'
    | '/admin/server'
    | '/admin/simulations'
    | '/admin/tools'
    | '/admin/users'
    | '/simulations/submit'
    | '/admin/tools/batch-email'
    | '/admin/tools/simulation-importer'
    | '/admin/tools/user-importer'
    | '/admin/users/$userId'
    | '/admin/users/$userId/folder'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_protected/admin'
    | '/_protected/simulations'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_public/about'
    | '/_public/analytics'
    | '/_public/guides'
    | '/_public/privacy'
    | '/_public/terms-of-service'
    | '/_public/'
    | '/_protected/admin/flags'
    | '/_protected/admin/simulations'
    | '/_protected/admin/tools'
    | '/_protected/admin/users'
    | '/_protected/simulations/submit'
    | '/_protected/admin/settings'
    | '/_protected/simulations/$simulationId'
    | '/_protected/simulations/'
    | '/_protected/admin/tools/batch-email'
    | '/_protected/admin/tools/simulation-importer'
    | '/_protected/admin/tools/user-importer'
    | '/_protected/admin/users/$userId'
    | '/_protected/admin/flags/$key'
    | '/_protected/admin/flags/new'
    | '/_protected/admin/simulations/$simulationId'
    | '/_protected/admin/flags/'
    | '/_protected/admin/server/'
    | '/_protected/admin/simulations/'
    | '/_protected/admin/tools/'
    | '/_protected/admin/users/'
    | '/_protected/simulations/submit/'
    | '/_protected/admin/tools/batch-email/'
    | '/_protected/admin/tools/simulation-importer/'
    | '/_protected/admin/tools/user-importer/'
    | '/_protected/admin/users/$userId/'
    | '/_protected/admin/users/$userId/folder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAnalyticsRoute: typeof PublicAnalyticsRoute
  PublicGuidesRoute: typeof PublicGuidesRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsOfServiceRoute: typeof PublicTermsOfServiceRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/terms-of-service': {
      id: '/_public/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof PublicTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/guides': {
      id: '/_public/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof PublicGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/analytics': {
      id: '/_public/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof PublicAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/simulations': {
      id: '/_protected/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof ProtectedSimulationsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/simulations/': {
      id: '/_protected/simulations/'
      path: '/'
      fullPath: '/simulations/'
      preLoaderRoute: typeof ProtectedSimulationsIndexRouteImport
      parentRoute: typeof ProtectedSimulationsRouteRoute
    }
    '/_protected/simulations/$simulationId': {
      id: '/_protected/simulations/$simulationId'
      path: '/$simulationId'
      fullPath: '/simulations/$simulationId'
      preLoaderRoute: typeof ProtectedSimulationsSimulationIdRouteImport
      parentRoute: typeof ProtectedSimulationsRouteRoute
    }
    '/_protected/admin/settings': {
      id: '/_protected/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof ProtectedAdminSettingsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/simulations/submit': {
      id: '/_protected/simulations/submit'
      path: '/submit'
      fullPath: '/simulations/submit'
      preLoaderRoute: typeof ProtectedSimulationsSubmitRouteRouteImport
      parentRoute: typeof ProtectedSimulationsRouteRoute
    }
    '/_protected/admin/users': {
      id: '/_protected/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/tools': {
      id: '/_protected/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof ProtectedAdminToolsRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/simulations': {
      id: '/_protected/admin/simulations'
      path: '/simulations'
      fullPath: '/admin/simulations'
      preLoaderRoute: typeof ProtectedAdminSimulationsRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/flags': {
      id: '/_protected/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof ProtectedAdminFlagsRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/simulations/submit/': {
      id: '/_protected/simulations/submit/'
      path: '/'
      fullPath: '/simulations/submit/'
      preLoaderRoute: typeof ProtectedSimulationsSubmitIndexRouteImport
      parentRoute: typeof ProtectedSimulationsSubmitRouteRoute
    }
    '/_protected/admin/users/': {
      id: '/_protected/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof ProtectedAdminUsersIndexRouteImport
      parentRoute: typeof ProtectedAdminUsersRouteRoute
    }
    '/_protected/admin/tools/': {
      id: '/_protected/admin/tools/'
      path: '/'
      fullPath: '/admin/tools/'
      preLoaderRoute: typeof ProtectedAdminToolsIndexRouteImport
      parentRoute: typeof ProtectedAdminToolsRouteRoute
    }
    '/_protected/admin/simulations/': {
      id: '/_protected/admin/simulations/'
      path: '/'
      fullPath: '/admin/simulations/'
      preLoaderRoute: typeof ProtectedAdminSimulationsIndexRouteImport
      parentRoute: typeof ProtectedAdminSimulationsRouteRoute
    }
    '/_protected/admin/server/': {
      id: '/_protected/admin/server/'
      path: '/server'
      fullPath: '/admin/server/'
      preLoaderRoute: typeof ProtectedAdminServerIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/flags/': {
      id: '/_protected/admin/flags/'
      path: '/'
      fullPath: '/admin/flags/'
      preLoaderRoute: typeof ProtectedAdminFlagsIndexRouteImport
      parentRoute: typeof ProtectedAdminFlagsRouteRoute
    }
    '/_protected/admin/simulations/$simulationId': {
      id: '/_protected/admin/simulations/$simulationId'
      path: '/$simulationId'
      fullPath: '/admin/simulations/$simulationId'
      preLoaderRoute: typeof ProtectedAdminSimulationsSimulationIdRouteImport
      parentRoute: typeof ProtectedAdminSimulationsRouteRoute
    }
    '/_protected/admin/flags/new': {
      id: '/_protected/admin/flags/new'
      path: '/new'
      fullPath: '/admin/flags/new'
      preLoaderRoute: typeof ProtectedAdminFlagsNewRouteImport
      parentRoute: typeof ProtectedAdminFlagsRouteRoute
    }
    '/_protected/admin/flags/$key': {
      id: '/_protected/admin/flags/$key'
      path: '/$key'
      fullPath: '/admin/flags/$key'
      preLoaderRoute: typeof ProtectedAdminFlagsKeyRouteImport
      parentRoute: typeof ProtectedAdminFlagsRouteRoute
    }
    '/_protected/admin/users/$userId': {
      id: '/_protected/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof ProtectedAdminUsersUserIdRouteRouteImport
      parentRoute: typeof ProtectedAdminUsersRouteRoute
    }
    '/_protected/admin/tools/user-importer': {
      id: '/_protected/admin/tools/user-importer'
      path: '/user-importer'
      fullPath: '/admin/tools/user-importer'
      preLoaderRoute: typeof ProtectedAdminToolsUserImporterRouteRouteImport
      parentRoute: typeof ProtectedAdminToolsRouteRoute
    }
    '/_protected/admin/tools/simulation-importer': {
      id: '/_protected/admin/tools/simulation-importer'
      path: '/simulation-importer'
      fullPath: '/admin/tools/simulation-importer'
      preLoaderRoute: typeof ProtectedAdminToolsSimulationImporterRouteRouteImport
      parentRoute: typeof ProtectedAdminToolsRouteRoute
    }
    '/_protected/admin/tools/batch-email': {
      id: '/_protected/admin/tools/batch-email'
      path: '/batch-email'
      fullPath: '/admin/tools/batch-email'
      preLoaderRoute: typeof ProtectedAdminToolsBatchEmailRouteRouteImport
      parentRoute: typeof ProtectedAdminToolsRouteRoute
    }
    '/_protected/admin/users/$userId/': {
      id: '/_protected/admin/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof ProtectedAdminUsersUserIdIndexRouteImport
      parentRoute: typeof ProtectedAdminUsersUserIdRouteRoute
    }
    '/_protected/admin/tools/user-importer/': {
      id: '/_protected/admin/tools/user-importer/'
      path: '/'
      fullPath: '/admin/tools/user-importer/'
      preLoaderRoute: typeof ProtectedAdminToolsUserImporterIndexRouteImport
      parentRoute: typeof ProtectedAdminToolsUserImporterRouteRoute
    }
    '/_protected/admin/tools/simulation-importer/': {
      id: '/_protected/admin/tools/simulation-importer/'
      path: '/'
      fullPath: '/admin/tools/simulation-importer/'
      preLoaderRoute: typeof ProtectedAdminToolsSimulationImporterIndexRouteImport
      parentRoute: typeof ProtectedAdminToolsSimulationImporterRouteRoute
    }
    '/_protected/admin/tools/batch-email/': {
      id: '/_protected/admin/tools/batch-email/'
      path: '/'
      fullPath: '/admin/tools/batch-email/'
      preLoaderRoute: typeof ProtectedAdminToolsBatchEmailIndexRouteImport
      parentRoute: typeof ProtectedAdminToolsBatchEmailRouteRoute
    }
    '/_protected/admin/users/$userId/folder/': {
      id: '/_protected/admin/users/$userId/folder/'
      path: '/folder'
      fullPath: '/admin/users/$userId/folder/'
      preLoaderRoute: typeof ProtectedAdminUsersUserIdFolderIndexRouteImport
      parentRoute: typeof ProtectedAdminUsersUserIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedAdminFlagsRouteRouteChildren {
  ProtectedAdminFlagsKeyRoute: typeof ProtectedAdminFlagsKeyRoute
  ProtectedAdminFlagsNewRoute: typeof ProtectedAdminFlagsNewRoute
  ProtectedAdminFlagsIndexRoute: typeof ProtectedAdminFlagsIndexRoute
}

const ProtectedAdminFlagsRouteRouteChildren: ProtectedAdminFlagsRouteRouteChildren =
  {
    ProtectedAdminFlagsKeyRoute: ProtectedAdminFlagsKeyRoute,
    ProtectedAdminFlagsNewRoute: ProtectedAdminFlagsNewRoute,
    ProtectedAdminFlagsIndexRoute: ProtectedAdminFlagsIndexRoute,
  }

const ProtectedAdminFlagsRouteRouteWithChildren =
  ProtectedAdminFlagsRouteRoute._addFileChildren(
    ProtectedAdminFlagsRouteRouteChildren,
  )

interface ProtectedAdminSimulationsRouteRouteChildren {
  ProtectedAdminSimulationsSimulationIdRoute: typeof ProtectedAdminSimulationsSimulationIdRoute
  ProtectedAdminSimulationsIndexRoute: typeof ProtectedAdminSimulationsIndexRoute
}

const ProtectedAdminSimulationsRouteRouteChildren: ProtectedAdminSimulationsRouteRouteChildren =
  {
    ProtectedAdminSimulationsSimulationIdRoute:
      ProtectedAdminSimulationsSimulationIdRoute,
    ProtectedAdminSimulationsIndexRoute: ProtectedAdminSimulationsIndexRoute,
  }

const ProtectedAdminSimulationsRouteRouteWithChildren =
  ProtectedAdminSimulationsRouteRoute._addFileChildren(
    ProtectedAdminSimulationsRouteRouteChildren,
  )

interface ProtectedAdminToolsBatchEmailRouteRouteChildren {
  ProtectedAdminToolsBatchEmailIndexRoute: typeof ProtectedAdminToolsBatchEmailIndexRoute
}

const ProtectedAdminToolsBatchEmailRouteRouteChildren: ProtectedAdminToolsBatchEmailRouteRouteChildren =
  {
    ProtectedAdminToolsBatchEmailIndexRoute:
      ProtectedAdminToolsBatchEmailIndexRoute,
  }

const ProtectedAdminToolsBatchEmailRouteRouteWithChildren =
  ProtectedAdminToolsBatchEmailRouteRoute._addFileChildren(
    ProtectedAdminToolsBatchEmailRouteRouteChildren,
  )

interface ProtectedAdminToolsSimulationImporterRouteRouteChildren {
  ProtectedAdminToolsSimulationImporterIndexRoute: typeof ProtectedAdminToolsSimulationImporterIndexRoute
}

const ProtectedAdminToolsSimulationImporterRouteRouteChildren: ProtectedAdminToolsSimulationImporterRouteRouteChildren =
  {
    ProtectedAdminToolsSimulationImporterIndexRoute:
      ProtectedAdminToolsSimulationImporterIndexRoute,
  }

const ProtectedAdminToolsSimulationImporterRouteRouteWithChildren =
  ProtectedAdminToolsSimulationImporterRouteRoute._addFileChildren(
    ProtectedAdminToolsSimulationImporterRouteRouteChildren,
  )

interface ProtectedAdminToolsUserImporterRouteRouteChildren {
  ProtectedAdminToolsUserImporterIndexRoute: typeof ProtectedAdminToolsUserImporterIndexRoute
}

const ProtectedAdminToolsUserImporterRouteRouteChildren: ProtectedAdminToolsUserImporterRouteRouteChildren =
  {
    ProtectedAdminToolsUserImporterIndexRoute:
      ProtectedAdminToolsUserImporterIndexRoute,
  }

const ProtectedAdminToolsUserImporterRouteRouteWithChildren =
  ProtectedAdminToolsUserImporterRouteRoute._addFileChildren(
    ProtectedAdminToolsUserImporterRouteRouteChildren,
  )

interface ProtectedAdminToolsRouteRouteChildren {
  ProtectedAdminToolsBatchEmailRouteRoute: typeof ProtectedAdminToolsBatchEmailRouteRouteWithChildren
  ProtectedAdminToolsSimulationImporterRouteRoute: typeof ProtectedAdminToolsSimulationImporterRouteRouteWithChildren
  ProtectedAdminToolsUserImporterRouteRoute: typeof ProtectedAdminToolsUserImporterRouteRouteWithChildren
  ProtectedAdminToolsIndexRoute: typeof ProtectedAdminToolsIndexRoute
}

const ProtectedAdminToolsRouteRouteChildren: ProtectedAdminToolsRouteRouteChildren =
  {
    ProtectedAdminToolsBatchEmailRouteRoute:
      ProtectedAdminToolsBatchEmailRouteRouteWithChildren,
    ProtectedAdminToolsSimulationImporterRouteRoute:
      ProtectedAdminToolsSimulationImporterRouteRouteWithChildren,
    ProtectedAdminToolsUserImporterRouteRoute:
      ProtectedAdminToolsUserImporterRouteRouteWithChildren,
    ProtectedAdminToolsIndexRoute: ProtectedAdminToolsIndexRoute,
  }

const ProtectedAdminToolsRouteRouteWithChildren =
  ProtectedAdminToolsRouteRoute._addFileChildren(
    ProtectedAdminToolsRouteRouteChildren,
  )

interface ProtectedAdminUsersUserIdRouteRouteChildren {
  ProtectedAdminUsersUserIdIndexRoute: typeof ProtectedAdminUsersUserIdIndexRoute
  ProtectedAdminUsersUserIdFolderIndexRoute: typeof ProtectedAdminUsersUserIdFolderIndexRoute
}

const ProtectedAdminUsersUserIdRouteRouteChildren: ProtectedAdminUsersUserIdRouteRouteChildren =
  {
    ProtectedAdminUsersUserIdIndexRoute: ProtectedAdminUsersUserIdIndexRoute,
    ProtectedAdminUsersUserIdFolderIndexRoute:
      ProtectedAdminUsersUserIdFolderIndexRoute,
  }

const ProtectedAdminUsersUserIdRouteRouteWithChildren =
  ProtectedAdminUsersUserIdRouteRoute._addFileChildren(
    ProtectedAdminUsersUserIdRouteRouteChildren,
  )

interface ProtectedAdminUsersRouteRouteChildren {
  ProtectedAdminUsersUserIdRouteRoute: typeof ProtectedAdminUsersUserIdRouteRouteWithChildren
  ProtectedAdminUsersIndexRoute: typeof ProtectedAdminUsersIndexRoute
}

const ProtectedAdminUsersRouteRouteChildren: ProtectedAdminUsersRouteRouteChildren =
  {
    ProtectedAdminUsersUserIdRouteRoute:
      ProtectedAdminUsersUserIdRouteRouteWithChildren,
    ProtectedAdminUsersIndexRoute: ProtectedAdminUsersIndexRoute,
  }

const ProtectedAdminUsersRouteRouteWithChildren =
  ProtectedAdminUsersRouteRoute._addFileChildren(
    ProtectedAdminUsersRouteRouteChildren,
  )

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminFlagsRouteRoute: typeof ProtectedAdminFlagsRouteRouteWithChildren
  ProtectedAdminSimulationsRouteRoute: typeof ProtectedAdminSimulationsRouteRouteWithChildren
  ProtectedAdminToolsRouteRoute: typeof ProtectedAdminToolsRouteRouteWithChildren
  ProtectedAdminUsersRouteRoute: typeof ProtectedAdminUsersRouteRouteWithChildren
  ProtectedAdminSettingsRoute: typeof ProtectedAdminSettingsRoute
  ProtectedAdminServerIndexRoute: typeof ProtectedAdminServerIndexRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminFlagsRouteRoute: ProtectedAdminFlagsRouteRouteWithChildren,
  ProtectedAdminSimulationsRouteRoute:
    ProtectedAdminSimulationsRouteRouteWithChildren,
  ProtectedAdminToolsRouteRoute: ProtectedAdminToolsRouteRouteWithChildren,
  ProtectedAdminUsersRouteRoute: ProtectedAdminUsersRouteRouteWithChildren,
  ProtectedAdminSettingsRoute: ProtectedAdminSettingsRoute,
  ProtectedAdminServerIndexRoute: ProtectedAdminServerIndexRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedSimulationsSubmitRouteRouteChildren {
  ProtectedSimulationsSubmitIndexRoute: typeof ProtectedSimulationsSubmitIndexRoute
}

const ProtectedSimulationsSubmitRouteRouteChildren: ProtectedSimulationsSubmitRouteRouteChildren =
  {
    ProtectedSimulationsSubmitIndexRoute: ProtectedSimulationsSubmitIndexRoute,
  }

const ProtectedSimulationsSubmitRouteRouteWithChildren =
  ProtectedSimulationsSubmitRouteRoute._addFileChildren(
    ProtectedSimulationsSubmitRouteRouteChildren,
  )

interface ProtectedSimulationsRouteRouteChildren {
  ProtectedSimulationsSubmitRouteRoute: typeof ProtectedSimulationsSubmitRouteRouteWithChildren
  ProtectedSimulationsSimulationIdRoute: typeof ProtectedSimulationsSimulationIdRoute
  ProtectedSimulationsIndexRoute: typeof ProtectedSimulationsIndexRoute
}

const ProtectedSimulationsRouteRouteChildren: ProtectedSimulationsRouteRouteChildren =
  {
    ProtectedSimulationsSubmitRouteRoute:
      ProtectedSimulationsSubmitRouteRouteWithChildren,
    ProtectedSimulationsSimulationIdRoute:
      ProtectedSimulationsSimulationIdRoute,
    ProtectedSimulationsIndexRoute: ProtectedSimulationsIndexRoute,
  }

const ProtectedSimulationsRouteRouteWithChildren =
  ProtectedSimulationsRouteRoute._addFileChildren(
    ProtectedSimulationsRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedSimulationsRouteRoute: typeof ProtectedSimulationsRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedSimulationsRouteRoute: ProtectedSimulationsRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicAboutRoute: PublicAboutRoute,
  PublicAnalyticsRoute: PublicAnalyticsRoute,
  PublicGuidesRoute: PublicGuidesRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsOfServiceRoute: PublicTermsOfServiceRoute,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
