/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppSubmitIndexRouteImport } from './routes/app/submit/index'
import { Route as ApphomeIndexRouteImport } from './routes/app/(home)/index'
import { Route as AppSimulationsSimulationIdRouteImport } from './routes/app/simulations/$simulationId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSubmitIndexRoute = AppSubmitIndexRouteImport.update({
  id: '/submit/',
  path: '/submit/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApphomeIndexRoute = ApphomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSimulationsSimulationIdRoute =
  AppSimulationsSimulationIdRouteImport.update({
    id: '/simulations/$simulationId',
    path: '/simulations/$simulationId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/terms': typeof TermsIndexRoute
  '/app/simulations/$simulationId': typeof AppSimulationsSimulationIdRoute
  '/app/': typeof ApphomeIndexRoute
  '/app/submit': typeof AppSubmitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/terms': typeof TermsIndexRoute
  '/app/simulations/$simulationId': typeof AppSimulationsSimulationIdRoute
  '/app': typeof ApphomeIndexRoute
  '/app/submit': typeof AppSubmitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/app/simulations/$simulationId': typeof AppSimulationsSimulationIdRoute
  '/app/(home)/': typeof ApphomeIndexRoute
  '/app/submit/': typeof AppSubmitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/analytics'
    | '/guides'
    | '/privacy'
    | '/terms'
    | '/app/simulations/$simulationId'
    | '/app/'
    | '/app/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/analytics'
    | '/guides'
    | '/privacy'
    | '/terms'
    | '/app/simulations/$simulationId'
    | '/app'
    | '/app/submit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/analytics/'
    | '/guides/'
    | '/privacy/'
    | '/terms/'
    | '/app/simulations/$simulationId'
    | '/app/(home)/'
    | '/app/submit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/submit/': {
      id: '/app/submit/'
      path: '/submit'
      fullPath: '/app/submit'
      preLoaderRoute: typeof AppSubmitIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(home)/': {
      id: '/app/(home)/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof ApphomeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/simulations/$simulationId': {
      id: '/app/simulations/$simulationId'
      path: '/simulations/$simulationId'
      fullPath: '/app/simulations/$simulationId'
      preLoaderRoute: typeof AppSimulationsSimulationIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppSimulationsSimulationIdRoute: typeof AppSimulationsSimulationIdRoute
  ApphomeIndexRoute: typeof ApphomeIndexRoute
  AppSubmitIndexRoute: typeof AppSubmitIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSimulationsSimulationIdRoute: AppSimulationsSimulationIdRoute,
  ApphomeIndexRoute: ApphomeIndexRoute,
  AppSubmitIndexRoute: AppSubmitIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
