version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  simple-mail:
    build: .
    restart: always
    ports:
      - '3002:3000'
    env_file: .env
    volumes:
      - simple-mail:/data
volumes:
  cache:
    driver: local
  simple-mail:
    driver: local