FROM nvidia/cuda:12.2.0-devel-ubuntu22.04 as base
WORKDIR /home/gromacs

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install python3-pip grace cmake gcc wget -y

RUN wget https://ftp.gromacs.org/gromacs/gromacs-2023.2.tar.gz
RUN tar -xf gromacs-2023.2.tar.gz

FROM base as gromacs_build_and_deps
WORKDIR /home/gromacs/gromacs-2023.2
RUN mkdir build
WORKDIR /home/gromacs/gromacs-2023.2/build
# If the host machine doesn't have CUDA capabilities, you can change '-DGMX_GPU' to any ot the supported values
# specified at GROMACS' documentation. You also can remove the parameter completely to build GROMACS to run on CPU.
RUN cmake .. -DGMX_GPU=CUDA -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON -DGMX_DOUBLE=OFF
RUN make -j6
RUN make -j6 check
RUN make install

RUN chmod +x /usr/local/gromacs/bin/gmx

ENV PATH=$PATH:/usr/local/gromacs/bin


FROM gromacs_build_and_deps as requirements_install
WORKDIR /var/www/server
COPY ./requirements.txt .
RUN pip install -r requirements.txt

FROM requirements_install as runner
ENV GMX_MAXBACKUP=-1
COPY . .
