FROM gromacs/gromacs

WORKDIR /var/www/server

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install python3-pip grace -y

COPY . .

RUN pip install -r requirements.txt

