import classes from "./terms-of-service.module.css";

import { Box } from "@mantine/core";
import { createFileRoute } from "@tanstack/react-router";

import { LanderCallToActionSection } from "./-components/CallToActionSection";
import { LanderLayout } from "./-components/Layout";

import { Heading } from "@/components/Heading";
import { buildSeoHead, DEFAULT_SITE_URL } from "@/lib/seo";
import { loadRuntimeSeoData } from "@/lib/seo.runtime";

export const Route = createFileRoute("/_public/terms-of-service")({
  loader: () => loadRuntimeSeoData(),
  head: ({ loaderData }) =>
    buildSeoHead({
      title: "Terms of Use",
      description:
        "Visual Dynamics terms of use — rules and conditions for using the service.",
      path: "/terms-of-service",
      index: false,
      siteUrl: loaderData?.siteUrl ?? DEFAULT_SITE_URL,
    }),
  component: RouteComponent,
});

function RouteComponent() {
  return (
    <LanderLayout>
      <Heading centered title="Terms of Use" />
      <Box className={classes.content}>
        <Section title="1. Acceptance of Terms">
          <p>
            By accessing and using the Visual Dynamics platform, you agree to
            these Terms of Use. If you do not agree with any provision herein,
            do not use the platform. These Terms of Use constitute a binding
            agreement between you and Fiocruz, through LABIOQUIM.
          </p>
        </Section>

        <Section title="2. Service Description">
          <p>
            Visual Dynamics is a free web platform for visualization, analysis,
            and simulation of molecular dynamics of biomolecules. The platform
            enables researchers to run simulations directly in the browser,
            without the need to install specialized software.
          </p>
        </Section>

        <Section title="3. Registration and Account">
          <p>
            To use the platform, you must create an account by providing true,
            accurate, and complete information. You are responsible for
            maintaining the confidentiality of your access credentials and for
            all activities carried out under your account. In the event of
            unauthorized use, notify us immediately.
          </p>
        </Section>

        <Section title="4. User Obligations">
          <p>By using the platform, you agree to:</p>
          <ul>
            <li>Not use the platform for unlawful or unauthorized purposes;</li>
            <li>
              Not upload files that contain malicious content, viruses, or any
              harmful code;
            </li>
            <li>
              Not attempt to gain unauthorized access to restricted areas of the
              platform, servers, or connected networks;
            </li>
            <li>
              Respect intellectual property laws applicable to the molecular
              structures and data submitted;
            </li>
            <li>
              Not intentionally overload the infrastructure with excessive
              simultaneous simulations that harm other users.
            </li>
          </ul>
        </Section>

        <Section title="5. Intellectual Property">
          <p>
            The Visual Dynamics platform, including its source code, design,
            logo, text, and other visual elements, is the property of
            Fiocruz/LABIOQUIM, protected by Brazilian copyright and intellectual
            property law.
          </p>
          <p>
            The data and results generated by you through the platform remain
            under your ownership. Fiocruz does not claim ownership over the
            molecular structures, simulation parameters, or results produced by
            the user. However, by using the platform, you grant Fiocruz a
            non-exclusive license to process, store, and transmit this data
            solely to enable the provision of the service.
          </p>
        </Section>

        <Section title="6. Limitation of Liability">
          <p>
            The platform is provided "as is." Fiocruz offers no warranties as to
            uninterrupted availability, accuracy of simulation results, or
            suitability of the platform for specific purposes. Under no
            circumstances shall Fiocruz be liable for indirect, incidental, or
            consequential damages arising from the use or inability to use the
            platform.
          </p>
        </Section>

        <Section title="7. Changes to Terms">
          <p>
            We reserve the right to modify these Terms of Use at any time.
            Changes take effect upon publication on this page. Continued use of
            the platform after publication constitutes acceptance of the
            modified terms. We recommend periodically reviewing this page.
          </p>
        </Section>

        <Section title="8. Suspension and Termination">
          <p>
            Fiocruz reserves the right to unilaterally suspend or terminate
            access for users who violate these Terms of Use or use the platform
            abusively, with prior notice whenever possible. You may terminate
            your account at any time by contacting us. Your data will be handled
            in accordance with our Privacy Policy.
          </p>
        </Section>

        <Section title="9. Governing Law and Jurisdiction">
          <p>
            These Terms of Use are governed by the laws of the Federative
            Republic of Brazil. To settle any disputes arising from these Terms,
            the District Court of Rio de Janeiro — RJ is hereby elected, with
            express waiver of any other, however privileged it may be.
          </p>
        </Section>

        <Section title="10. Contact">
          <p>
            For questions, suggestions, or communications related to these Terms
            of Use, please contact:
          </p>
          <p>
            <strong>Email:</strong> visualdynamics@fiocruz.br
          </p>
        </Section>

        <p className={classes.lastUpdated}>Last updated: July 25, 2026.</p>
      </Box>
      <LanderCallToActionSection />
    </LanderLayout>
  );
}

function Section({
  children,
  title,
}: {
  children: React.ReactNode;
  title: string;
}) {
  return (
    <div className={classes.section}>
      <h2 className={classes.sectionTitle}>{title}</h2>
      {children}
    </div>
  );
}
